//------------------------------------------------------------------------------
// <auto-generated>

using System;
using System.Collections.Generic;

namespace WebApplication1
{
    
    
    public partial class AccountsLog
    {
        public int ID { get; set; }
        public string EventType { get; set; }
        public string TableName { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        
        public AccountsLog (string oprationType,string tablename,DateTime createddate)
        {
            this.EventType = oprationType;
            this.TableName = tablename;
            this.Created_date = createddate;
        }
    }

   
}
